### ISSUE TITLE
无法使用tim的db，是否不兼容tim？

### ISSUE THREAD

**Issue by cuihua0** [zsqw123/QQ-Exp-Android#3]
已给root权限

不复制文件，输入我的账号和别人的账号以后点粉色的导出按钮，然后出现0.0%，然后瞬间变成导出按钮，然后查看，没有导出文件。

手动复制/data/data/com.tencent.tim/databases里面的xxxxx.db和slowtable_xxxxx.db到/storage/emulated/0/Android/data/qhaty.qqex/files，点粉色的导出按钮，会提示：
"检测到已导入过聊天数据文件，需要删除重建吗"
不管选取消还是确认，都会提示qqex已停止运行，并且没有导出文件

**Comment by cuihua0** [comment]
已找到问题，不支持模拟器给的root权限
提示android.permission.ACCESS.SUPERUSER在manifest中未定义
取消root权限，用re管理器把文件复制出来，手动输入kc key就可以了

**Comment by zsqw123** [comment]
你这么一说, 我是默认用我这个软件的人都装了QQ了hhhhc  
TIM支持完全没问题, 只是最近在忙别的事情没空

**Comment by cuihua0** [comment]
> 你这么一说, 我是默认用我这个软件的人都装了QQ了hhhhc
> TIM支持完全没问题, 只是最近在忙别的事情没空

好的，谢谢
